### ISSUE TITLE
package.json issue: no such file or directory, open package.json

### ISSUE THREAD

**Issue by anandshenoy14** [sdras/js-explorer#2]
Following Issue is Observed when using `jsexplorer` command in the below mentioned specs

![image](https://user-images.githubusercontent.com/1655091/125403314-40e94500-e36a-11eb-826f-0bda4d6d548d.png)

OS: MacOS Mojave
Node: v12.22.3
NPM: v7.19.1

**Comment by anandshenoy14** [comment]
#3

**Comment by sdras** [comment]
merged! thank you
